export const tokens = {
  cssVariableNames: [
    'background',
    'foreground',
    'card',
    'card-foreground',
    'popover',
    'popover-foreground',
    'primary',
    'primary-foreground',
    'secondary',
    'secondary-foreground',
    'muted',
    'muted-foreground',
    'accent',
    'accent-foreground',
    'destructive',
    'destructive-foreground',
    'success',
    'success-foreground',
    'warning',
    'warning-foreground',
    'border',
    'input',
    'ring',
    'chart-up',
    'chart-down',
    'chart-volume',
    'risk',
    'info',
    'radius',
    'font-sans',
    'font-mono',
    'elevation-sm',
    'elevation-md',
  ],
  colors: {
    bg: 'hsl(var(--background))',
    surface: 'hsl(var(--card))',
    text: 'hsl(var(--foreground))',
    textMuted: 'hsl(var(--muted-foreground))',
    border: 'hsl(var(--border))',
    primary: 'hsl(var(--primary))',
    accent: 'hsl(var(--accent))',
    positive: 'hsl(var(--success))',
    negative: 'hsl(var(--destructive))',
    warning: 'hsl(var(--warning))',
    info: 'hsl(var(--info))',
  },
  typography: {
    fontFamily: 'var(--font-sans)',
    monoFamily: 'var(--font-mono)',
    scale: {
      xs: 12,
      sm: 13,
      md: 14,
      lg: 16,
      xl: 20,
      xxl: 28,
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      tight: 1.1,
      normal: 1.4,
      relaxed: 1.6,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  layout: {
    gridRowHeight: 120,
    contentMaxWidth: 1280,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 12,
  },
  elevation: {
    sm: 'var(--elevation-sm)',
    md: 'var(--elevation-md)',
  },
  chart: {
    up: 'hsl(var(--chart-up))',
    down: 'hsl(var(--chart-down))',
    volume: 'hsl(var(--chart-volume))',
    risk: 'hsl(var(--risk))',
  },
};

export type ThemeMode = 'dark' | 'light';
