package domain

import "time"

// Signal represents a trading signal generated by strategy analysis
type Signal struct {
	ID         string                 `json:"id"`
	Symbol     string                 `json:"symbol"`
	Timestamp  time.Time              `json:"timestamp"`
	Type       string                 `json:"type"` // "buy", "sell", "hold"
	Confidence float64                `json:"confidence"`
	EntryPrice float64                `json:"entry_price"`
	StopLoss   float64                `json:"stop_loss"`
	TakeProfit []float64              `json:"take_profit"`
	Reason     string                 `json:"reason"`
	StrategyID string                 `json:"strategy_id"`
	Indicators map[string]interface{} `json:"indicators"`
}
