// Package candidates manages candidate trade lifecycle for the always-on watcher.
package candidates

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Status values for a candidate trade.
const (
	StatusDetected         = "detected"
	StatusQualified        = "qualified"
	StatusBlocked          = "blocked"
	StatusAwaitingApproval = "awaiting_approval"
	StatusApproved         = "approved"
	StatusRejected         = "rejected"
	StatusExpired          = "expired"
	StatusSubmitted        = "submitted"
	StatusFilled           = "filled"
	StatusCancelled        = "cancelled"
)

// Candidate represents a trade setup generated by the watcher.
type Candidate struct {
	ID                     uuid.UUID        `json:"id"`
	StrategyInstanceID     uuid.UUID        `json:"strategyInstanceId"`
	SignalID               *uuid.UUID       `json:"signalId,omitempty"`
	StrategyID             *string          `json:"strategyId,omitempty"`
	ArtifactID             *uuid.UUID       `json:"artifactId,omitempty"`
	Symbol                 string           `json:"symbol"`
	SignalType             string           `json:"signalType"`
	Status                 string           `json:"status"`
	EntryPrice             *float64         `json:"entryPrice,omitempty"`
	StopLoss               *float64         `json:"stopLoss,omitempty"`
	TakeProfit             *float64         `json:"takeProfit,omitempty"`
	Confidence             *float64         `json:"confidence,omitempty"`
	Reasoning              *string          `json:"reasoning,omitempty"`
	BlockReason            *string          `json:"blockReason,omitempty"`
	BlockedReasonCode      *string          `json:"blockedReasonCode,omitempty"`
	SessionDate            string           `json:"sessionDate"`
	ExpiresAt              *time.Time       `json:"expiresAt,omitempty"`
	DetectedAt             time.Time        `json:"detectedAt"`
	QualifiedAt            *time.Time       `json:"qualifiedAt,omitempty"`
	BlockedAt              *time.Time       `json:"blockedAt,omitempty"`
	SubmittedAt            *time.Time       `json:"submittedAt,omitempty"`
	FilledAt               *time.Time       `json:"filledAt,omitempty"`
	DataProvenance         string           `json:"dataProvenance"`
	Metadata               *json.RawMessage `json:"metadata,omitempty"`
	LatestApproval         *ApprovalSummary `json:"latestApproval,omitempty"`
	ExecutionInstructionID *uuid.UUID       `json:"executionInstructionId,omitempty"`
	TradeID                *string          `json:"tradeId,omitempty"`
	CreatedAt              time.Time        `json:"createdAt"`
	UpdatedAt              time.Time        `json:"updatedAt"`
}

type ApprovalSummary struct {
	ID         uuid.UUID `json:"id"`
	Decision   string    `json:"decision"`
	ApprovedBy string    `json:"approvedBy"`
	DecidedAt  time.Time `json:"decidedAt"`
}

// Store handles persistence for candidates.
type Store struct {
	pool *pgxpool.Pool
}

// NewStore creates a new candidate Store.
func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool}
}

// Create inserts a new detected candidate and returns it.
func (s *Store) Create(ctx context.Context, c *Candidate) (*Candidate, error) {
	return s.createWithStatus(ctx, c, StatusDetected)
}

func (s *Store) CreateBlocked(ctx context.Context, c *Candidate) (*Candidate, error) {
	return s.createWithStatus(ctx, c, StatusBlocked)
}

func (s *Store) createWithStatus(ctx context.Context, c *Candidate, initialStatus string) (*Candidate, error) {
	if c.ID == uuid.Nil {
		c.ID = uuid.New()
	}
	if c.DataProvenance == "" {
		c.DataProvenance = "unknown"
	}
	now := time.Now().UTC()
	c.DetectedAt = now
	c.CreatedAt = now
	c.UpdatedAt = now
	if initialStatus == StatusBlocked && c.BlockedAt == nil {
		c.BlockedAt = &now
	}

	_, err := s.pool.Exec(ctx, `
		INSERT INTO candidate_trades (
			id, strategy_instance_id, signal_id, strategy_id, artifact_id, symbol, signal_type, status,
			entry_price, stop_loss, take_profit, confidence, reasoning,
			block_reason, blocked_reason_code, session_date, expires_at, detected_at,
			blocked_at,
			data_provenance, metadata, created_at, updated_at
		) VALUES (
			$1, $2, $3, $4, $5, $6, $7, $8,
			$9, $10, $11, $12, $13, $14,
			$15, $16, $17, $18, $19,
			$20, $21, $22, $23
		)`,
		c.ID, c.StrategyInstanceID, c.SignalID, c.StrategyID, c.ArtifactID, c.Symbol, c.SignalType, initialStatus,
		c.EntryPrice, c.StopLoss, c.TakeProfit, c.Confidence, c.Reasoning,
		c.BlockReason, c.BlockedReasonCode, c.SessionDate, c.ExpiresAt, c.DetectedAt,
		c.BlockedAt, c.DataProvenance, c.Metadata, c.CreatedAt, c.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("candidates.Store.Create: %w", err)
	}
	c.Status = initialStatus
	eventType := "created"
	if initialStatus == StatusBlocked {
		eventType = "blocked"
	}
	s.appendEvent(ctx, c.ID, eventType, "", initialStatus, nil)
	return c, nil
}

// UpdateStatus transitions a candidate to a new status.
func (s *Store) UpdateStatus(ctx context.Context, id uuid.UUID, toStatus string, extra map[string]any) error {
	var current Candidate
	row := s.pool.QueryRow(ctx, `SELECT id, status FROM candidate_trades WHERE id = $1`, id)
	if err := row.Scan(&current.ID, &current.Status); err != nil {
		return fmt.Errorf("candidates.Store.UpdateStatus find: %w", err)
	}

	now := time.Now().UTC()
	set := "status = $2, updated_at = $3"
	args := []any{id, toStatus, now}

	switch toStatus {
	case StatusQualified:
		set += fmt.Sprintf(", qualified_at = $%d", len(args)+1)
		args = append(args, now)
	case StatusBlocked:
		set += fmt.Sprintf(", blocked_at = $%d", len(args)+1)
		args = append(args, now)
		if reason, ok := extra["blockReason"].(string); ok {
			set += fmt.Sprintf(", block_reason = $%d", len(args)+1)
			args = append(args, reason)
		}
		if code, ok := extra["blockedReasonCode"].(string); ok {
			set += fmt.Sprintf(", blocked_reason_code = $%d", len(args)+1)
			args = append(args, code)
		}
	case StatusSubmitted:
		set += fmt.Sprintf(", submitted_at = $%d", len(args)+1)
		args = append(args, now)
	case StatusFilled:
		set += fmt.Sprintf(", filled_at = $%d", len(args)+1)
		args = append(args, now)
	}

	_, err := s.pool.Exec(ctx,
		fmt.Sprintf(`UPDATE candidate_trades SET %s WHERE id = $1`, set),
		args...,
	)
	if err != nil {
		return fmt.Errorf("candidates.Store.UpdateStatus: %w", err)
	}
	s.appendEvent(ctx, id, "status_change", current.Status, toStatus, extra)
	return nil
}

// GetByID returns a single candidate.
func (s *Store) GetByID(ctx context.Context, id uuid.UUID) (*Candidate, error) {
	row := s.pool.QueryRow(ctx, candidateSelectSQL+` WHERE id = $1`, id)
	return scanCandidate(row)
}

// List returns candidates, optionally filtered by status or symbol.
func (s *Store) List(ctx context.Context, status, symbol string, limit int) ([]*Candidate, error) {
	where := "WHERE 1=1"
	args := []any{}
	if status != "" {
		args = append(args, status)
		where += fmt.Sprintf(" AND status = $%d", len(args))
	}
	if symbol != "" {
		args = append(args, symbol)
		where += fmt.Sprintf(" AND symbol = $%d", len(args))
	}
	args = append(args, limit)
	query := candidateSelectSQL + " " + where + fmt.Sprintf(" ORDER BY detected_at DESC LIMIT $%d", len(args))
	rows, err := s.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("candidates.Store.List: %w", err)
	}
	defer rows.Close()
	var out []*Candidate
	for rows.Next() {
		c, err := scanCandidate(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// HasOpenForInstanceSymbol checks for an existing open candidate (dedup gate).
func (s *Store) HasOpenForInstanceSymbol(ctx context.Context, instanceID uuid.UUID, symbol, sessionDate string) (bool, error) {
	var count int
	err := s.pool.QueryRow(ctx, `
		SELECT COUNT(*) FROM candidate_trades
		WHERE strategy_instance_id = $1 AND symbol = $2 AND session_date = $3
		  AND status IN ('detected','qualified','awaiting_approval','approved')`,
		instanceID, symbol, sessionDate,
	).Scan(&count)
	return count > 0, err
}

// appendEvent writes a candidate_events row (best-effort, non-fatal).
func (s *Store) appendEvent(ctx context.Context, candidateID uuid.UUID, eventType, fromStatus, toStatus string, detail map[string]any) {
	var detailJSON *[]byte
	if len(detail) > 0 {
		b, _ := json.Marshal(detail)
		detailJSON = &b
	}
	_, _ = s.pool.Exec(ctx, `
		INSERT INTO candidate_events (candidate_id, event_type, from_status, to_status, detail)
		VALUES ($1, $2, $3, $4, $5)`,
		candidateID, eventType, fromStatus, toStatus, detailJSON,
	)
}

const candidateSelectSQL = `
SELECT
	id, strategy_instance_id, signal_id, strategy_id, artifact_id, symbol, signal_type, status,
	entry_price, stop_loss, take_profit, confidence, reasoning,
	block_reason, blocked_reason_code, session_date::text, expires_at, detected_at,
	qualified_at, blocked_at, submitted_at, filled_at,
	data_provenance, metadata,
	latest_approval_id, latest_approval_decision, latest_approval_by, latest_approval_at,
	execution_instruction_id, trade_id,
	created_at, updated_at
FROM (
	SELECT
		ct.id,
		ct.strategy_instance_id,
		ct.signal_id,
		ct.strategy_id,
		ct.artifact_id,
		ct.symbol,
		ct.signal_type,
		ct.status,
		ct.entry_price,
		ct.stop_loss,
		ct.take_profit,
		ct.confidence,
		ct.reasoning,
		ct.block_reason,
		ct.blocked_reason_code,
		ct.session_date,
		ct.expires_at,
		ct.detected_at,
		ct.qualified_at,
		ct.blocked_at,
		ct.submitted_at,
		ct.filled_at,
		ct.data_provenance,
		ct.metadata,
		la.id AS latest_approval_id,
		la.decision AS latest_approval_decision,
		la.approved_by AS latest_approval_by,
		la.decided_at AS latest_approval_at,
		ei.id AS execution_instruction_id,
		ei.trade_id,
		ct.created_at,
		ct.updated_at
	FROM candidate_trades ct
	LEFT JOIN LATERAL (
		SELECT id, decision, approved_by, decided_at
		FROM candidate_approvals
		WHERE candidate_id = ct.id
		ORDER BY decided_at DESC
		LIMIT 1
	) la ON TRUE
	LEFT JOIN LATERAL (
		SELECT id, trade_id
		FROM execution_instructions
		WHERE candidate_id = ct.id
		ORDER BY created_at DESC
		LIMIT 1
	) ei ON TRUE
) candidate_view`

func scanCandidate(row interface{ Scan(...any) error }) (*Candidate, error) {
	var c Candidate
	var (
		signalID, artifactID, approvalID, executionInstructionID                       uuid.NullUUID
		strategyID, blockReasonCode, latestApprovalDecision, latestApprovalBy, tradeID NullableString
		latestApprovalAt                                                               NullableTime
	)
	err := row.Scan(
		&c.ID, &c.StrategyInstanceID, &signalID, &strategyID, &artifactID, &c.Symbol, &c.SignalType, &c.Status,
		&c.EntryPrice, &c.StopLoss, &c.TakeProfit, &c.Confidence, &c.Reasoning,
		&c.BlockReason, &blockReasonCode, &c.SessionDate, &c.ExpiresAt, &c.DetectedAt,
		&c.QualifiedAt, &c.BlockedAt, &c.SubmittedAt, &c.FilledAt,
		&c.DataProvenance, &c.Metadata,
		&approvalID, &latestApprovalDecision, &latestApprovalBy, &latestApprovalAt,
		&executionInstructionID, &tradeID,
		&c.CreatedAt, &c.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("scanCandidate: %w", err)
	}
	assignUUIDPtr(signalID, &c.SignalID)
	assignUUIDPtr(artifactID, &c.ArtifactID)
	assignUUIDPtr(executionInstructionID, &c.ExecutionInstructionID)
	assignStringPtr(strategyID, &c.StrategyID)
	assignStringPtr(blockReasonCode, &c.BlockedReasonCode)
	assignStringPtr(tradeID, &c.TradeID)
	if approvalID.Valid && latestApprovalDecision.Valid {
		summary := &ApprovalSummary{
			ID:       approvalID.UUID,
			Decision: latestApprovalDecision.String,
		}
		if latestApprovalBy.Valid {
			summary.ApprovedBy = latestApprovalBy.String
		}
		if latestApprovalAt.Valid {
			summary.DecidedAt = latestApprovalAt.Time
		}
		c.LatestApproval = summary
	}
	return &c, nil
}

type NullableString struct {
	String string
	Valid  bool
}

func (n *NullableString) Scan(value any) error {
	if value == nil {
		n.String = ""
		n.Valid = false
		return nil
	}
	switch v := value.(type) {
	case string:
		n.String = v
	case []byte:
		n.String = string(v)
	default:
		return fmt.Errorf("unsupported string scan type %T", value)
	}
	n.Valid = strings.TrimSpace(n.String) != ""
	return nil
}

type NullableTime struct {
	Time  time.Time
	Valid bool
}

func (n *NullableTime) Scan(value any) error {
	if value == nil {
		n.Valid = false
		n.Time = time.Time{}
		return nil
	}
	switch v := value.(type) {
	case time.Time:
		n.Time = v
	default:
		return fmt.Errorf("unsupported time scan type %T", value)
	}
	n.Valid = true
	return nil
}

func assignUUIDPtr(value uuid.NullUUID, target **uuid.UUID) {
	if value.Valid {
		v := value.UUID
		*target = &v
		return
	}
	*target = nil
}

func assignStringPtr(value NullableString, target **string) {
	if value.Valid {
		v := value.String
		*target = &v
		return
	}
	*target = nil
}
