// Package candidates manages candidate trade lifecycle for the always-on watcher.
package candidates

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Status values for a candidate trade.
const (
	StatusDetected         = "detected"
	StatusQualified        = "qualified"
	StatusBlocked          = "blocked"
	StatusAwaitingApproval = "awaiting_approval"
	StatusApproved         = "approved"
	StatusRejected         = "rejected"
	StatusExpired          = "expired"
	StatusSubmitted        = "submitted"
	StatusFilled           = "filled"
	StatusCancelled        = "cancelled"
)

// Candidate represents a trade setup generated by the watcher.
type Candidate struct {
	ID                 uuid.UUID        `json:"id"`
	StrategyInstanceID uuid.UUID        `json:"strategyInstanceId"`
	Symbol             string           `json:"symbol"`
	SignalType         string           `json:"signalType"`
	Status             string           `json:"status"`
	EntryPrice         *float64         `json:"entryPrice,omitempty"`
	StopLoss           *float64         `json:"stopLoss,omitempty"`
	TakeProfit         *float64         `json:"takeProfit,omitempty"`
	Confidence         *float64         `json:"confidence,omitempty"`
	Reasoning          *string          `json:"reasoning,omitempty"`
	BlockReason        *string          `json:"blockReason,omitempty"`
	SessionDate        string           `json:"sessionDate"`
	ExpiresAt          *time.Time       `json:"expiresAt,omitempty"`
	DetectedAt         time.Time        `json:"detectedAt"`
	QualifiedAt        *time.Time       `json:"qualifiedAt,omitempty"`
	BlockedAt          *time.Time       `json:"blockedAt,omitempty"`
	SubmittedAt        *time.Time       `json:"submittedAt,omitempty"`
	FilledAt           *time.Time       `json:"filledAt,omitempty"`
	DataProvenance     string           `json:"dataProvenance"`
	Metadata           *json.RawMessage `json:"metadata,omitempty"`
	CreatedAt          time.Time        `json:"createdAt"`
	UpdatedAt          time.Time        `json:"updatedAt"`
}

// Store handles persistence for candidates.
type Store struct {
	pool *pgxpool.Pool
}

// NewStore creates a new candidate Store.
func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool}
}

// Create inserts a new detected candidate and returns it.
func (s *Store) Create(ctx context.Context, c *Candidate) (*Candidate, error) {
	if c.ID == uuid.Nil {
		c.ID = uuid.New()
	}
	if c.DataProvenance == "" {
		c.DataProvenance = "unknown"
	}
	now := time.Now().UTC()
	c.DetectedAt = now
	c.CreatedAt = now
	c.UpdatedAt = now

	_, err := s.pool.Exec(ctx, `
		INSERT INTO candidate_trades (
			id, strategy_instance_id, symbol, signal_type, status,
			entry_price, stop_loss, take_profit, confidence, reasoning,
			block_reason, session_date, expires_at, detected_at,
			data_provenance, metadata, created_at, updated_at
		) VALUES (
			$1, $2, $3, $4, $5,
			$6, $7, $8, $9, $10,
			$11, $12, $13, $14,
			$15, $16, $17, $18
		)`,
		c.ID, c.StrategyInstanceID, c.Symbol, c.SignalType, StatusDetected,
		c.EntryPrice, c.StopLoss, c.TakeProfit, c.Confidence, c.Reasoning,
		c.BlockReason, c.SessionDate, c.ExpiresAt, c.DetectedAt,
		c.DataProvenance, c.Metadata, c.CreatedAt, c.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("candidates.Store.Create: %w", err)
	}
	c.Status = StatusDetected
	s.appendEvent(ctx, c.ID, "created", "", StatusDetected, nil)
	return c, nil
}

// UpdateStatus transitions a candidate to a new status.
func (s *Store) UpdateStatus(ctx context.Context, id uuid.UUID, toStatus string, extra map[string]any) error {
	var current Candidate
	row := s.pool.QueryRow(ctx, `SELECT id, status FROM candidate_trades WHERE id = $1`, id)
	if err := row.Scan(&current.ID, &current.Status); err != nil {
		return fmt.Errorf("candidates.Store.UpdateStatus find: %w", err)
	}

	now := time.Now().UTC()
	set := "status = $2, updated_at = $3"
	args := []any{id, toStatus, now}

	switch toStatus {
	case StatusQualified:
		set += fmt.Sprintf(", qualified_at = $%d", len(args)+1)
		args = append(args, now)
	case StatusBlocked:
		set += fmt.Sprintf(", blocked_at = $%d", len(args)+1)
		args = append(args, now)
		if reason, ok := extra["blockReason"].(string); ok {
			set += fmt.Sprintf(", block_reason = $%d", len(args)+1)
			args = append(args, reason)
		}
	case StatusSubmitted:
		set += fmt.Sprintf(", submitted_at = $%d", len(args)+1)
		args = append(args, now)
	case StatusFilled:
		set += fmt.Sprintf(", filled_at = $%d", len(args)+1)
		args = append(args, now)
	}

	_, err := s.pool.Exec(ctx,
		fmt.Sprintf(`UPDATE candidate_trades SET %s WHERE id = $1`, set),
		args...,
	)
	if err != nil {
		return fmt.Errorf("candidates.Store.UpdateStatus: %w", err)
	}
	s.appendEvent(ctx, id, "status_change", current.Status, toStatus, extra)
	return nil
}

// GetByID returns a single candidate.
func (s *Store) GetByID(ctx context.Context, id uuid.UUID) (*Candidate, error) {
	row := s.pool.QueryRow(ctx, candidateSelectSQL+` WHERE id = $1`, id)
	return scanCandidate(row)
}

// List returns candidates, optionally filtered by status or symbol.
func (s *Store) List(ctx context.Context, status, symbol string, limit int) ([]*Candidate, error) {
	where := "WHERE 1=1"
	args := []any{}
	if status != "" {
		args = append(args, status)
		where += fmt.Sprintf(" AND status = $%d", len(args))
	}
	if symbol != "" {
		args = append(args, symbol)
		where += fmt.Sprintf(" AND symbol = $%d", len(args))
	}
	args = append(args, limit)
	query := candidateSelectSQL + " " + where + fmt.Sprintf(" ORDER BY detected_at DESC LIMIT $%d", len(args))
	rows, err := s.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("candidates.Store.List: %w", err)
	}
	defer rows.Close()
	var out []*Candidate
	for rows.Next() {
		c, err := scanCandidate(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// HasOpenForInstanceSymbol checks for an existing open candidate (dedup gate).
func (s *Store) HasOpenForInstanceSymbol(ctx context.Context, instanceID uuid.UUID, symbol, sessionDate string) (bool, error) {
	var count int
	err := s.pool.QueryRow(ctx, `
		SELECT COUNT(*) FROM candidate_trades
		WHERE strategy_instance_id = $1 AND symbol = $2 AND session_date = $3
		  AND status IN ('detected','qualified','awaiting_approval','approved')`,
		instanceID, symbol, sessionDate,
	).Scan(&count)
	return count > 0, err
}

// appendEvent writes a candidate_events row (best-effort, non-fatal).
func (s *Store) appendEvent(ctx context.Context, candidateID uuid.UUID, eventType, fromStatus, toStatus string, detail map[string]any) {
	var detailJSON *[]byte
	if len(detail) > 0 {
		b, _ := json.Marshal(detail)
		detailJSON = &b
	}
	_, _ = s.pool.Exec(ctx, `
		INSERT INTO candidate_events (candidate_id, event_type, from_status, to_status, detail)
		VALUES ($1, $2, $3, $4, $5)`,
		candidateID, eventType, fromStatus, toStatus, detailJSON,
	)
}

const candidateSelectSQL = `
SELECT
	id, strategy_instance_id, symbol, signal_type, status,
	entry_price, stop_loss, take_profit, confidence, reasoning,
	block_reason, session_date::text, expires_at, detected_at,
	qualified_at, blocked_at, submitted_at, filled_at,
	data_provenance, metadata, created_at, updated_at
FROM candidate_trades`

func scanCandidate(row interface{ Scan(...any) error }) (*Candidate, error) {
	var c Candidate
	err := row.Scan(
		&c.ID, &c.StrategyInstanceID, &c.Symbol, &c.SignalType, &c.Status,
		&c.EntryPrice, &c.StopLoss, &c.TakeProfit, &c.Confidence, &c.Reasoning,
		&c.BlockReason, &c.SessionDate, &c.ExpiresAt, &c.DetectedAt,
		&c.QualifiedAt, &c.BlockedAt, &c.SubmittedAt, &c.FilledAt,
		&c.DataProvenance, &c.Metadata, &c.CreatedAt, &c.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("scanCandidate: %w", err)
	}
	return &c, nil
}
