CREATE TABLE IF NOT EXISTS paper_orders (
    order_id TEXT PRIMARY KEY,
    contract_version TEXT NOT NULL,
    venue_id TEXT NOT NULL,
    environment TEXT NOT NULL CHECK (environment = 'PAPER'),
    paper_intent_id TEXT NOT NULL UNIQUE,
    workflow_id TEXT NOT NULL REFERENCES workflow_instances(workflow_id) ON DELETE RESTRICT,
    recommendation_id TEXT NOT NULL,
    risk_decision_id TEXT NOT NULL,
    confirmation_id TEXT NOT NULL,
    instrument_id TEXT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('LONG', 'SHORT')),
    quantity NUMERIC NOT NULL CHECK (quantity > 0),
    remaining_quantity NUMERIC NOT NULL CHECK (remaining_quantity >= 0),
    filled_quantity NUMERIC NOT NULL CHECK (filled_quantity >= 0),
    order_type TEXT NOT NULL CHECK (order_type IN ('MARKET', 'LIMIT')),
    limit_price NUMERIC,
    cost_model_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    activates_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('NEW', 'ACTIVE', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED')),
    CONSTRAINT chk_paper_order_quantity CHECK (filled_quantity + remaining_quantity = quantity),
    CONSTRAINT chk_paper_order_time_order CHECK (activates_at >= created_at)
);
